=== frohwerk/dbs7/bestand.dtd
<!ELEMENT bestand (artikelgruppen,artikelliste)>

<!ELEMENT artikelgruppen (artikelgruppe)*>

<!ELEMENT artikelgruppe (bezeichnung)>

<!ATTLIST artikelgruppe  gid  ID  #REQUIRED>
<!ELEMENT bezeichnung    (#PCDATA)>

<!ELEMENT artikelliste (artikel)*>

<!ELEMENT artikel (artbez,ekpreis,vpreis)>
<!ATTLIST artikel
        artnr  ID     #REQUIRED
        gid    IDREF  #REQUIRED>
<!ELEMENT artbez   (#PCDATA)>
<!ELEMENT ekpreis  (#PCDATA)>
<!ATTLIST ekpreis  currency  (EUR|DOL|YEN|YUAN)  "EUR">
<!ELEMENT vpreis   (#PCDATA)>
<!ATTLIST vpreis   currency  (EUR|DOL|YEN|YUAN)  "EUR">

=== frohwerk/dbs7/bestand.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bestand SYSTEM "bestand.dtd">
<bestand>
    <artikelgruppen>
        <artikelgruppe gid="G10">
            <bezeichnung>Workstation</bezeichnung>
        </artikelgruppe>
        <artikelgruppe gid="G20">
            <bezeichnung>Server</bezeichnung>
        </artikelgruppe>
        <artikelgruppe gid="G30">
            <bezeichnung>Monitor</bezeichnung>
        </artikelgruppe>
    </artikelgruppen>
    <artikelliste>
        <artikel artnr="A1000" gid="G10">
            <artbez>Transtec 800</artbez>
            <ekpreis>720.00</ekpreis>
            <vpreis>749.00</vpreis>
        </artikel>
        <artikel artnr="A1100" gid="G30">
            <artbez>Trinitron 17"</artbez>
            <ekpreis>375.00</ekpreis>
            <vpreis>399.00</vpreis>
        </artikel>
    </artikelliste>
</bestand>
